from __future__ import annotations

import sys

from .audit import (
    architecture_omission_reason_exists,
    audit_change_packet,
    audit_decision_entry_completeness,
    audit_project,
    audit_readme_documentation_map,
    audit_roadmap_acceptance,
    audit_spec_decision_table,
    block_has_content,
    checkbox_counts,
    cmd_audit,
    cmd_new_decision,
    cmd_status,
    current_phase_from_roadmap,
    decision_sections,
    decision_skeleton,
    discover_change_packets,
    docs_rel_for_markdown,
    extract_decision_ids,
    labeled_block_body,
    markdown_cells,
    markdown_section,
    markdown_separator_row,
    parse_current_status,
    roadmap_step_sections,
    section_has_real_table_row,
)
from .commands import build_parser, main
from .models import Finding
from .paths import (
    CHANGE_OPTIONAL_DOC_NAMES,
    CHANGE_REQUIRED_DOC_NAMES,
    CHANGES_SUBDIR,
    DEFAULT_DOCS_DIR,
    DOC_NAMES,
    GENERATED_SUBDIR,
    SKILL_NAME,
    VERSION,
    changes_dir_for,
    docs_dir_for,
    find_source_root,
    generated_dir_for,
    path_from_env,
    project_root_from_module,
    read_config,
    skill_source_dir,
)
from .release import (
    UninstallAction,
    cmd_uninstall,
    cmd_update,
    launcher_is_docdev_owned,
    plan_native_uninstall,
)
from .sync import (
    cmd_doctor,
    cmd_sync_skill,
    copy_skill,
    parse_targets,
    target_path_for,
)
from .templates import (
    change_template_dir_for,
    cmd_init,
    cmd_new_change,
    copy_template,
    ensure_agents_pointer,
    ensure_readme_pointer,
    normalize_slug,
    template_dir_for,
)


def eprint(message: str) -> None:
    print(message, file=sys.stderr)


__all__ = [
    "CHANGE_OPTIONAL_DOC_NAMES",
    "CHANGE_REQUIRED_DOC_NAMES",
    "CHANGES_SUBDIR",
    "DEFAULT_DOCS_DIR",
    "DOC_NAMES",
    "Finding",
    "GENERATED_SUBDIR",
    "SKILL_NAME",
    "UninstallAction",
    "VERSION",
    "architecture_omission_reason_exists",
    "audit_change_packet",
    "audit_decision_entry_completeness",
    "audit_project",
    "audit_readme_documentation_map",
    "audit_roadmap_acceptance",
    "audit_spec_decision_table",
    "block_has_content",
    "build_parser",
    "change_template_dir_for",
    "changes_dir_for",
    "checkbox_counts",
    "cmd_audit",
    "cmd_doctor",
    "cmd_init",
    "cmd_new_change",
    "cmd_new_decision",
    "cmd_status",
    "cmd_sync_skill",
    "cmd_uninstall",
    "cmd_update",
    "copy_skill",
    "copy_template",
    "current_phase_from_roadmap",
    "decision_sections",
    "decision_skeleton",
    "discover_change_packets",
    "docs_dir_for",
    "docs_rel_for_markdown",
    "eprint",
    "ensure_agents_pointer",
    "ensure_readme_pointer",
    "extract_decision_ids",
    "find_source_root",
    "generated_dir_for",
    "labeled_block_body",
    "launcher_is_docdev_owned",
    "main",
    "markdown_cells",
    "markdown_section",
    "markdown_separator_row",
    "normalize_slug",
    "parse_current_status",
    "parse_targets",
    "path_from_env",
    "plan_native_uninstall",
    "project_root_from_module",
    "read_config",
    "roadmap_step_sections",
    "section_has_real_table_row",
    "skill_source_dir",
    "target_path_for",
    "template_dir_for",
]


if __name__ == "__main__":
    raise SystemExit(main())
