from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .paths import path_from_env, find_source_root
from .sync import target_path_for


@dataclass(frozen=True)
class UninstallAction:
    label: str
    path: Path
    action: str
    reason: str


def cmd_update(args: argparse.Namespace) -> int:
    source_root = find_source_root()
    if os.name == "nt":
        installer = source_root / "scripts" / "install_remote.ps1"
    else:
        installer = source_root / "scripts" / "install_remote.sh"
    if not installer.exists():
        raise SystemExit(f"Native installer script missing: {installer}")

    if os.name == "nt":
        command = ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(installer)]
        if args.version:
            command.extend(["-Version", args.version])
        if args.release_base_url:
            command.extend(["-ReleaseBaseUrl", args.release_base_url])
        if args.install_root:
            command.extend(["-InstallRoot", args.install_root])
        if args.bin_dir:
            command.extend(["-BinDir", args.bin_dir])
        if args.sync_skill:
            command.append("-SyncSkill")
        else:
            command.append("-NoSyncSkill")
    else:
        command = [str(installer)]
        if args.version:
            command.extend(["--version", args.version])
        if args.release_base_url:
            command.extend(["--release-base-url", args.release_base_url])
        if args.install_root:
            command.extend(["--install-root", args.install_root])
        if args.bin_dir:
            command.extend(["--bin-dir", args.bin_dir])
        if args.sync_skill:
            command.append("--sync-skill")
        else:
            command.append("--no-sync-skill")

    env = os.environ.copy()
    env.setdefault("DOCDEV_INSTALL_LOG_PREFIX", "[docdev update]")
    return subprocess.run(command, check=False, env=env).returncode


def resolve_install_root(raw: str | None = None) -> Path:
    if raw:
        return Path(raw).expanduser()
    env = path_from_env("DOCDEV_INSTALL_ROOT")
    if env is not None:
        return env
    return Path.home() / ".local" / "share" / "docdev"


def resolve_bin_dir(raw: str | None = None) -> Path:
    if raw:
        return Path(raw).expanduser()
    env = path_from_env("DOCDEV_BIN_DIR")
    if env is not None:
        return env
    return Path.home() / ".local" / "bin"


def launcher_candidates(bin_dir: Path) -> list[Path]:
    return [bin_dir / "docdev", bin_dir / "docdev.ps1", bin_dir / "docdev.cmd"]


def dangerous_removal_path(path: Path) -> bool:
    resolved = path.expanduser().resolve(strict=False)
    try:
        home = Path.home().resolve(strict=False)
    except OSError:
        home = Path.home()
    return resolved in {
        Path("/"),
        home,
        home / ".local",
        home / ".local" / "share",
        home / ".local" / "bin",
        home / ".codex",
        home / ".cursor",
        home / ".agents",
        home / ".claude",
    }


def launcher_is_docdev_owned(path: Path) -> bool:
    if not path.exists() and not path.is_symlink():
        return False
    if path.is_symlink():
        return True
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")[:4096]
    except OSError:
        return False
    return "docs_driven_dev.cli" in text and ("DOCDEV_PROJECT_DIR" in text or "PYTHONPATH" in text)


def plan_native_uninstall(
    install_root: Path,
    bin_dir: Path,
    keep_skills: bool,
    targets: tuple[str, ...] = ("codex", "cursor", "agents", "claude"),
) -> list[UninstallAction]:
    actions: list[UninstallAction] = []

    if install_root.exists() or install_root.is_symlink():
        if dangerous_removal_path(install_root):
            actions.append(UninstallAction("install root", install_root, "skip", "unsafe parent path"))
        else:
            actions.append(UninstallAction("install root", install_root, "remove", "native release install root"))
    else:
        actions.append(UninstallAction("install root", install_root, "skip", "missing"))

    for launcher in launcher_candidates(bin_dir):
        if not launcher.exists() and not launcher.is_symlink():
            actions.append(UninstallAction("launcher", launcher, "skip", "missing"))
        elif launcher_is_docdev_owned(launcher):
            actions.append(UninstallAction("launcher", launcher, "remove", "generated docdev launcher"))
        else:
            actions.append(UninstallAction("launcher", launcher, "skip", "not generated by docdev"))

    if keep_skills:
        actions.append(UninstallAction("skill targets", Path("(all)"), "skip", "--keep-skills"))
        return actions

    seen: set[Path] = set()
    for target in targets:
        path = target_path_for(target)
        key = path.expanduser().absolute()
        if key in seen:
            continue
        seen.add(key)
        label = f"skill {target}"
        if path.is_symlink():
            actions.append(UninstallAction(label, path, "remove", "owned symlink target"))
        elif path.exists() and (path / ".docdev-skill-source").exists():
            actions.append(UninstallAction(label, path, "remove", "marked docs-driven-dev skill target"))
        elif path.exists():
            actions.append(UninstallAction(label, path, "skip", "unmarked skill target"))
        else:
            actions.append(UninstallAction(label, path, "skip", "missing"))

    return actions


def remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.exists():
        shutil.rmtree(path)


def print_uninstall_plan(actions: list[UninstallAction]) -> None:
    print("docdev uninstall plan:")
    for item in actions:
        print(f"  {item.action}: {item.label}: {item.path} ({item.reason})")


def cmd_uninstall(args: argparse.Namespace) -> int:
    install_root = resolve_install_root(args.install_root)
    bin_dir = resolve_bin_dir(args.bin_dir)
    actions = plan_native_uninstall(install_root, bin_dir, keep_skills=args.keep_skills)
    print_uninstall_plan(actions)

    if args.dry_run:
        return 0
    if not args.yes:
        print("Refusing to uninstall without --yes. Use --dry-run to preview only.", file=sys.stderr)
        return 2

    for item in actions:
        if item.action == "remove":
            remove_path(item.path)
            print(f"removed: {item.path}")
        else:
            print(f"skipped: {item.path} ({item.reason})")
    return 0
